const stores = [
  {
    type: "ethernet",
    item: "COF 8001 (Jumper Wire)",
    itemcode: "055738",
    image: "",
  },
  {
    type: "ethernet",
    item: "COF 8002 (Internal Cable)",
    itemcode: "055740",
    image: "",
  },
  {
    type: "ethernet",
    item: "Yellow Kevlar Restraints (10 Pack)",
    itemcode: "075869",
    image: "",
  },
  {
    type: "ethernet",
    item: "2A Shelf",
    itemcode: "075837",
    image: "",
  },
  {
    type: "ethernet",
    item: "3A Shelf",
    itemcode: "023901",
    image: "",
  },
  {
    type: "ethernet",
    item: "Multi Circuit Box (12 Trays)",
    itemcode: "007277",
    image: "",
  },
  {
    type: "ethernet",
    item: "Dual Circuit Box (Blownfibre / COF)",
    itemcode: "076020",
    image: "",
  },
  {
    type: "ethernet",
    item: "6 FDP Splicing Box",
    itemcode: "062655",
    image: "",
  },
  {
    type: "ethernet",
    item: "19 Inch Shelf",
    itemcode: "001847",
    image: "",
  },
  {
    type: "ethernet",
    item: "Blown Fibre Gas Seal Box",
    itemcode: "076024",
    image: "",
  },
  {
    type: "newsites",
    item: "Customer Splicing Panel(CSP)",
    itemcode: "100632",
    image: "",
  },
  {
    type: "newsites",
    item: "ONT - NOKIA",
    itemcode: "108260",
    image: "",
  },
  {
    type: "newsites",
    item: "ONT Case - NOKIA",
    itemcode: "101554",
    image: "",
  },
  {
    type: "newsites",
    item: "ONT - ADTRAN",
    itemcode: "111093",
    image: "",
  },
  {
    type: "newsites",
    item: "ONT Case - ADTRAN",
    itemcode: "112969",
    image: "",
  },
  {
    type: "newsites",
    item: "Capping - Foot",
    itemcode: "095096",
    image: "",
  },
  {
    type: "newsites",
    item: "Capping - Long",
    itemcode: "000000",
    image: "",
  },
  {
    type: "newsites",
    item: "Splitter 2 x 32 - Blue Legs",
    itemcode: "088364",
    image: "",
  },
  {
    type: "exchange",
    item: "Yellow Kevlar Restraints (10 Pack)",
    itemcode: "075869",
    image: "",
  },
  {
    type: "exchange",
    item: "OCR - Subrack",
    itemcode: "050641",
    image: "",
  },
  {
    type: "exchange",
    item: "OCR - WDM Tray",
    itemcode: "060809",
    image: "",
  },
  {
    type: "exchange",
    item: "OCR - Breakout Kit (for tie cables)",
    itemcode: "000000",
    image: "",
  },
  {
    type: "exchange",
    item: "OCR - Black Keys (10 PK)",
    itemcode: "105245",
    image: "",
  },
  {
    type: "exchange",
    item: "Patch Panel - SC/APC",
    itemcode: "046054",
    image: "",
  },
  {
    type: "exchange",
    item: "Patch Panel - LC/UPC",
    itemcode: "057161",
    image: "",
  },
  {
    type: "exchange",
    item: "Patch Panel - SC/PC",
    itemcode: "044893",
    image: "",
  },
  {
    type: "newsites",
    item: "Splitter 2 x 32 - Orange Legs",
    itemcode: "088365",
    image: "",
  },
  {
    type: "newsites",
    item: "Splitter 2 x 32 - Green Legs",
    itemcode: "104942",
    image: "",
  },
  {
    type: "newsites",
    item: "Splitter 2 x 32 - Red Legs",
    itemcode: "104943",
    image: "",
  },
  {
    type: "overhead",
    item: "ELM (Figure of 8 Anti Creepage)",
    itemcode: "066611",
    image: "",
  },
  {
    type: "overhead",
    item: "36F Clamp(10 PK)",
    itemcode: "085656",
    image: "",
  },
  {
    type: "overhead",
    item: "Pole Mounted Node Bracket (S/M)",
    itemcode: "088359",
    image: "",
  },
  {
    type: "overhead",
    item: "Letter and Punch Set",
    itemcode: "105489",
    image: "",
  },
  {
    type: "overhead",
    item: "Aluminium Strips 16x80 (25 PK)",
    itemcode: "015708",
    image: "",
  },
  {
    type: "overhead",
    item: "Aluminium Strips 16x120 (25 PK)",
    itemcode: "076077",
    image: "",
  },
  {
    type: "overhead",
    item: "Aluminium Strips 16x160 (25 PK)",
    itemcode: "076078",
    image: "",
  },
  {
    type: "overhead",
    item: "Pole Label Pins",
    itemcode: "070864",
    image: "",
  },
  {
    type: "overhead",
    item: "Pole Nails",
    itemcode: "072034",
    image: "",
  },
  {
    type: "overhead",
    item: "Pole Washers",
    itemcode: "073202",
    image: "",
  },
  {
    type: "tools",
    item: "Snips",
    itemcode: "093883",
    image: "",
  },
  {
    type: "tools",
    item: "Fibre Strippers - 3 in 1",
    itemcode: "127224",
    image: "",
  },
  {
    type: "tools",
    item: "Kevlar Scissors",
    itemcode: "080470",
    image: "",
  },
  {
    type: "tools",
    item: "No Nicks - BFT Tube Interceptor ",
    itemcode: "127256",
    image: "",
  },
  {
    type: "tools",
    item: "36F Stripper",
    itemcode: "088338",
    image: "",
  },
  {
    type: "tools",
    item: "36F Replacement Blades",
    itemcode: "088339",
    image: "",
  },
  {
    type: "tools",
    item: "COF250 Stripper",
    itemcode: "087376",
    image: "",
  },
  {
    type: "tools",
    item: "COF250 Replacement Blades (10 PK)",
    itemcode: "091802",
    image: "",
  },
  {
    type: "tools",
    item: "Dismantling Knife (Safety Knife)",
    itemcode: "105282",
    image: "",
  },
  {
    type: "tools",
    item: "Toolbox",
    itemcode: "013787",
    image: "",
  },
  {
    type: "nodes",
    item: "Small Node",
    itemcode: "092753",
    image: "",
  },
  {
    type: "nodes",
    item: "Medium Node",
    itemcode: "092756",
    image: "",
  },
  {
    type: "nodes",
    item: "Large Node (No Trays)",
    itemcode: "100184",
    image: "",
  },
  {
    type: "nodes",
    item: "Extra Large Node (No Trays)",
    itemcode: "100183",
    image: "",
  },
  {
    type: "nodes",
    item: "L / XL Node Trays",
    itemcode: "100185",
    image: "",
  },
  {
    type: "nodes",
    item: "3A Node - Single Circuit Trays",
    itemcode: "006827",
    image: "",
  },
  {
    type: "nodes",
    item: "3A Node - Element Trays",
    itemcode: "053211",
    image: "",
  },
  {
    type: "nodes",
    item: "36F Port Kit",
    itemcode: "088362",
    image: "",
  },
  {
    type: "nodes",
    item: "COF200 Port Kit",
    itemcode: "082322",
    image: "",
  },
  {
    type: "nodes",
    item: "COF250 (Slippy Fish / CBT) Port Kit",
    itemcode: "088363",
    image: "",
  },
  {
    type: "nodes",
    item: "COF260 Overblow Port Kit",
    itemcode: "082323",
    image: "",
  },
  {
    type: "nodes",
    item: "Cable Chamber Port Kit",
    itemcode: "091081",
    image: "",
  },
  {
    type: "nodes",
    item: "COF600 Port Kit",
    itemcode: "092760",
    image: "",
  },
  {
    type: "consumables",
    item: "White Spirit",
    itemcode: "",
    image: "",
  },
  {
    type: "consumables",
    item: "Blue Roll",
    itemcode: "",
    image: "",
  },
  {
    type: "consumables",
    item: "Yellow Tape",
    itemcode: "",
    image: "",
  },
  {
    type: "consumables",
    item: "Black Pen",
    itemcode: "",
    image: "",
  },
  {
    type: "consumables",
    item: "Gold Pen",
    itemcode: "",
    image: "",
  },
  {
    type: "consumables",
    item: "Cables Ties - Black",
    itemcode: "",
    image: "",
  },
  {
    type: "consumables",
    item: "Cables Ties - White",
    itemcode: "",
    image: "",
  },
  {
    type: "consumables",
    item: "Cable Ties - White",
    itemcode: "",
    image: "",
  },
  {
    type: "misc",
    item: "Green Light",
    itemcode: "",
    image: "",
  },
  {
    type: "misc",
    item: "Gate Guard",
    itemcode: "",
    image: "",
  },
  {
    type: "misc",
    item: "Roller Bar",
    itemcode: "",
    image: "",
  },
  {
    type: "misc",
    item: "Yellow Box Lifter",
    itemcode: "",
    image: "",
  },
];

export { stores };
